{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vistring",
    "module": "method-trace-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "method-trace-plugin-1.0.0.jar",
          "url": "method-trace-plugin-1.0.0.jar",
          "size": 36239,
          "sha512": "6f4e676530e668de8da6bc706186e59c1ff533a727e506f000a40bc886fd1cd0ecbac6eed23e6d9c445c3fc6bd66d3b13612ee3b53092cc817244f18eab80b26",
          "sha256": "056a0af464f58f6a49d81fe32d607d46ca673004a7a451342eb690c18a9d7fc2",
          "sha1": "5ea94942b93bf05989a04e933de90a26426ccc51",
          "md5": "ee3be03e6c810b53b747567778d7a076"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.joom.grip",
          "module": "grip",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.26.0-GA"
          }
        },
        {
          "group": "com.github.gundy",
          "module": "semver4j",
          "version": {
            "requires": "0.16.4"
          }
        }
      ],
      "files": [
        {
          "name": "method-trace-plugin-1.0.0.jar",
          "url": "method-trace-plugin-1.0.0.jar",
          "size": 36239,
          "sha512": "6f4e676530e668de8da6bc706186e59c1ff533a727e506f000a40bc886fd1cd0ecbac6eed23e6d9c445c3fc6bd66d3b13612ee3b53092cc817244f18eab80b26",
          "sha256": "056a0af464f58f6a49d81fe32d607d46ca673004a7a451342eb690c18a9d7fc2",
          "sha1": "5ea94942b93bf05989a04e933de90a26426ccc51",
          "md5": "ee3be03e6c810b53b747567778d7a076"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "method-trace-plugin-1.0.0-sources.jar",
          "url": "method-trace-plugin-1.0.0-sources.jar",
          "size": 6895,
          "sha512": "52de245c45fbe3591e0788d19aa69d662a29779b48e8bfd6e5c6b2c8f2de24967acba1a9389d4531cf41f4f824729dafd84ae94b12b4ad4f9de468ad88c5c3f6",
          "sha256": "6e29bcd1e7bcc44b92c97f0c9fa77ef84b45a13bc5fc8123b968456f989f0b2e",
          "sha1": "a3bd1c6ff832f4cf8d9789a39bb885cde3b041a6",
          "md5": "9f90a2f14f858ad17e66d44c385860ca"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "method-trace-plugin-1.0.0-javadoc.jar",
          "url": "method-trace-plugin-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "19c8fdefa1b7a737f25b000991ee07d1143bfcd83ae73c1f44aeb855e932f6eeb122e505febfaf9ffb57dd5a7874e40346ca6b8603f77fe08b34f4f64c9be322",
          "sha256": "85162aaf9a5869dbed8fafe14d69a3cc27b7aeef2eae06f3e199fdaf195859fd",
          "sha1": "1027b345270b0c31925be51861c3716daa932abe",
          "md5": "f12483877b37241abd6f20a1ce411110"
        }
      ]
    }
  ]
}
