{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vistring",
    "module": "method-trace-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "method-trace-plugin-1.0.0.jar",
          "url": "method-trace-plugin-1.0.0.jar",
          "size": 34363,
          "sha512": "98cb454c871f9b6f09713390f19cf339f10105963a4d49eacb1ee0cf6559998e55d4ea538cf665f81a486a1a5acff97ee4e7a12f9725ab1439199a0264b5d846",
          "sha256": "99628a7da30aa63f71a7d1721d785bd3aa429d48a64b28b42ac4951757d2b9fe",
          "sha1": "5735579a224624eff6fa42ced89a5b1f266dffae",
          "md5": "c1e546ebf22e017d0d5398f60eab7aa4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.4"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "com.joom.grip",
          "module": "grip",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.26.0-GA"
          }
        },
        {
          "group": "com.github.gundy",
          "module": "semver4j",
          "version": {
            "requires": "0.16.4"
          }
        }
      ],
      "files": [
        {
          "name": "method-trace-plugin-1.0.0.jar",
          "url": "method-trace-plugin-1.0.0.jar",
          "size": 34363,
          "sha512": "98cb454c871f9b6f09713390f19cf339f10105963a4d49eacb1ee0cf6559998e55d4ea538cf665f81a486a1a5acff97ee4e7a12f9725ab1439199a0264b5d846",
          "sha256": "99628a7da30aa63f71a7d1721d785bd3aa429d48a64b28b42ac4951757d2b9fe",
          "sha1": "5735579a224624eff6fa42ced89a5b1f266dffae",
          "md5": "c1e546ebf22e017d0d5398f60eab7aa4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "method-trace-plugin-1.0.0-sources.jar",
          "url": "method-trace-plugin-1.0.0-sources.jar",
          "size": 6528,
          "sha512": "d2d7e187b5b951c7983193a919c327053a3216d766da1a505ebaded634e4259b99b486f2136f1ca4221f4a61c734f8e7b1c6d5c981f3683adcb811df822254cc",
          "sha256": "a84e72dcdcc1d4a8a4a1d22bcad9dd9f61f43485a5d57c39e63cdfc30fedd589",
          "sha1": "e062aa54377285cc1552e21ff747a66ff22bde7e",
          "md5": "414b02de52492e423bf991e8fe91d065"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "method-trace-plugin-1.0.0-javadoc.jar",
          "url": "method-trace-plugin-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "ca39e457567b05de3d6a3bb833836f2954baa87d4bb4b05841fb94e6a4c2aab430a3180e7a7db5d2dc978e051f25b64e4bb04a0105c7c74af80dfc602d5f4d06",
          "sha256": "b78884f20569670a8084e5ace7020f7b36f8c457723b7ff129d2542551157f23",
          "sha1": "a6bf347cc0e634ebfe6a2651f9fa52a4eb66ebb4",
          "md5": "d69256422e18dac8bc22acdf6b928106"
        }
      ]
    }
  ]
}
