{
  "formatVersion": "1.1",
  "component": {
    "group": "com.vistring",
    "module": "method-trace",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "method-trace-1.0.0.aar",
          "url": "method-trace-1.0.0.aar",
          "size": 5733,
          "sha512": "e8d4fdede68794a6be80e2c53f4dae7104971cb5f45682db8dc4c71ef98841cdbab5ab06a3462e91a108fb720ff4c3360b07bdbf357cfbbe8dfddca1a6e90ef5",
          "sha256": "1aea539ad4d6df43eaf4504b02b8b97e8c60d37e078a1f8683a80a98c8031f85",
          "sha1": "2ee3d216e5923898d9021f206c04851285cbb560",
          "md5": "3533eb87ee7e7e8d9624db7b1798ed7a"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "method-trace-1.0.0.aar",
          "url": "method-trace-1.0.0.aar",
          "size": 5733,
          "sha512": "e8d4fdede68794a6be80e2c53f4dae7104971cb5f45682db8dc4c71ef98841cdbab5ab06a3462e91a108fb720ff4c3360b07bdbf357cfbbe8dfddca1a6e90ef5",
          "sha256": "1aea539ad4d6df43eaf4504b02b8b97e8c60d37e078a1f8683a80a98c8031f85",
          "sha1": "2ee3d216e5923898d9021f206c04851285cbb560",
          "md5": "3533eb87ee7e7e8d9624db7b1798ed7a"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "method-trace-1.0.0-sources.jar",
          "url": "method-trace-1.0.0-sources.jar",
          "size": 2859,
          "sha512": "f9197022c1726854c03fa34577e99396f3ac2b44cd74979dab258ae709017dd75153721cd5b5980f9723b9e13ae2a5fa34d0f6b4cd0439a84d1bac3b5fb88708",
          "sha256": "696aa558ecc64862900c0ee37f43e05f8bd23c036d4068dd9c2c9b9e63ea1457",
          "sha1": "65a29b3fd4708bac3cf77c3551c25942dfb81ceb",
          "md5": "fcee88d1dc3de0d762b7e8e1c5aabc5a"
        }
      ]
    }
  ]
}
